---
# fichier de tâches pour helloworld

- name: Copie du dossier de candidature
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copie du fichier upstart
  copy:
    src: helloworld.conf
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644

- name: Démarrage du service de nœud HelloWorld
  service:
    name: helloworld
    state: started
