---
# fichier de tâches pour jenkins
- name: Suppression de l'ancienne version de JAVA d'Amazon Linux
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Installer une version spécifique prise en charge de JAVA
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Ajouter un référentiel Jenkins
  shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo

- name: Importer la clé Jenkins GPG
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Installer Jenkins
  yum:
    name: jenkins-2.99
    enablerepo: jenkins
    state: present

- name: Démarrer Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
